mod-name: NearFutureExploration
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - NearFutureExploration
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.1.3
    location: s3
  B9PartSwitch:
    version: 2.12.1
    location: s3
deploy:
  SpaceDock:
    enabled: false  # activate/deactivate this deployment script
    mod-id: 2305  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: false  # activate/deactivate this deployment script
    mod-id: 241040  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
